### ISSUE TITLE
generust adds extra new lines

### ISSUE THREAD

**Issue by vurhanau** [devpts00/generust#3]
It generates files with extra new lines:
```
$ head -n 10 output.csv 
0,64.129.69.150,Male,myrealbox.com,three

1,119.88.81.146,Male,outlook.com.gr,one

2,93.235.215.2,Female,imaginemail.com,three

3,102.135.128.39,Male,inorbit.com,three
```

Is there a way to get rid of extra new lines?

**Comment by devpts00** [comment]
that's probably `echo` adds a new line, try `echo -n`, I can strip the newline from the template, but if somebody wants to have extra newline that can be a blocker

**Comment by vurhanau** [comment]
Yep, `cat` adds a new line. `echo -n` works fine.
